### ISSUE TITLE
Retain broken

### ISSUE THREAD

**Issue by mcbain** [henhal/serverless-plugin-layer-manager#2]
Can your plugin fix https://github.com/serverless/serverless/issues/6769?

**Comment by henhal** [comment]
The plugin doesn't deal with the actual creation or deletion of CF resources, so no I'm afraid not. It merely fixes some issues in the pre-deploy step related to referencing individual layer versions (which, indeed, is useful when using retain: true).

**Comment by mcbain** [comment]
Thanks, currently only a downgrade of serverless to 1.43.0 works for me
